import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/TheHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="{inter.className} grid grid-cols-6">
				<div className="dark:bg-gray-700 dark:text-white col-span-1">
					<Header />
				</div>
				<div className="col-span-5 ">{children}</div>
			</body>
		</html>
	);
}
